url = "http://127.0.0.1:8227"
external_nodes = []
[agent]
# Total available funds
# 10000 CKB
available_funds = "0xE8D4A51000"
interval = 15
max_chan_num = 100
max_pending = 20
# 100 CKB
min_chan_funds = "0x2540BE400"
# 100 CKB
max_chan_funds = "0x2540BE400"
[[agent.heuristics]]
heuristic = "Centrality"
weight = 0.8
[[agent.heuristics]]
heuristic = "Richness"
weight = 0.1
[[agent.heuristics]]
heuristic = "Random"
weight = 0.1
